#cloud-config
autoinstall:
  version: 1
  update: yes
  locale: en_US.UTF-8
  identity:
    hostname: node0-day0
    password: "$6$rounds=4096$saltsaltlettuce$Lp/FV.2oOgew7GbM6Nr8KMGMBn7iFM0x9ZwLqtx9Y4QJmKvfcnS.2zx4MKmymCPQGpHS7gqYOiqWjvdCIV2uN."
    username: maintenance
  ssh:
    allow-pw: false
    install-server: true
  packages:
    - python3-pip
    - python3.10-venv
    - ufw
  snaps:
    - name: microk8s
      channel: 1.26/stable
      classic: true
  late-commands:
    - ln -s /cdrom/secrets /target/root/secrets
    - curtin in-target --target=/target -- /bin/bash curl -fsSL https://tailscale.com/install.sh | sh
    - curtin in-target --target=/target -- /bin/bash tailscale up --authkey $(cat /root/secrets/tailscale_authkey)
    - rm -f /target/root/tailscale_apikey
  user-data: # Cloud-init starts here
    disable_root: true
    users:
      - name: maintenance
        groups: users, admin, docker, sudo
        sudo: ALL=(ALL) NOPASSWD:ALL
        shell: /bin/bash
        lock_passwd: true
        passwd: "$6$rounds=4096$saltsaltlettuce$Lp/FV.2oOgew7GbM6Nr8KMGMBn7iFM0x9ZwLqtx9Y4QJmKvfcnS.2zx4MKmymCPQGpHS7gqYOiqWjvdCIV2uN."
